baseURL: "https://88mangos.github.io/" 
title: Tyler Yang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Events
          url: events/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Creative
          url: creative/
          weight: 3

params:
    description: "This website hosts Tyler Yang's resume, academic history, and personal reading list/notes."
    author: Tyler Yang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","courses","papers","books"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Tyler Yang
          subtitle: "I am a sophomore at Carnegie Mellon University's School of Computer Science. I do research in machine learning for drug discovery, and more generally AI for Science. Currently interning at Scale AI."
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            # - name: Books
            #   url: books/
            - name: Events
              url: events/
            - name: Creative
              url: creative/

    socialIcons:
        - name: Resume
          url: resume-tylery.pdf
        - name: Email
          url: mailto:tylery@andrew.cmu.edu
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=oRAc9acAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/88Mangos
        - name: YouTube
          url: https://www.youtube.com/@tylery7041
    assets:
        disableScrollBarStyle: true
        favicon16x16: "favicon-16x16.png"
        # optional additional sizes:
        favicon32x32: "favicon-32x32.png"
        appleTouchIcon: "apple-touch-icon.png"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Tyler Yang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2