# =========================================================================== #
# Global Hugo Settings
# =========================================================================== #
baseURL: "https://88mangos.github.io/" 
title: tyler yang
theme: PaperMod # see themes/PaperMod

# =========================================================================== #
# Hugo Core Features
# =========================================================================== #
enableInlineShortcodes: true 
enableRobotsTXT: true

# set number of posts per page 
pagination:
  pagerSize: 20 
# as well as tags folder
taxonomies:
    tag: tags

# =========================================================================== #
# PaperMod Theme Parameters
# =========================================================================== #
params:
    description: "Tyler Yang's Personal Website"
    MainSections: ["coursework", "projects"]

    # googleAnalyticsID: "G-XXXXX"

    # ======================================================================= #
    # Appearance
    # ======================================================================= #
    DateFormat: "January 2006"
    hideFooter: true
    disableAnchoredHeadings: true # hide hashtag anchor symbols next to headings
    
    # Dark Mode, no toggle
    defaultTheme: dark
    disableThemeToggle: true
    
    # ======================================================================= #
    # User Quality of Life 
    # ======================================================================= #
    ShowCodeCopyButtons: true
    disableScrollToTop: true 
    math: true # MathJax/KaTeX support

    # ======================================================================= #
    # Post-Related Stuff
    # ======================================================================= #
    # author: Tyler Yang # don't want to show author, it's just me anyways
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowAllPagesInArchive: false
    ShowWordCount: false

    # see layouts/_default/list.html
    hideSummary: true
    hideMeta: false
    comments: false # no post comments

    
    ShowToc: false            # no table of contents
                              # thus options below are irrelevant
    TocOpen: true 
    UseHugoToc: true
    cover:                    # visibility of post cover images
        hidden: true
        hiddenInList: true
        hiddenInSingle: true
    label:                    # adds label to cover images 
      text: "Tyler Yang"  
      icon: favicon.ico
      iconHeight: 18

# =========================================================================== #
# Homepage
# Profile Mode instead of default blog list homepage
# =========================================================================== # 
    profileMode: 
          enabled: true
          title: Tyler Yang
          subtitle: "Studying @ CMU School of Computer Science <br><br>I like the number 8, mangos, and playing soccer, hence the GitHub username and icons on this personal website. <br><br>This personal website documents my experiences through coursework and projects, and doubles as a central hub for helpful resources. <br><br>Check out [<u>88Mangos</u>](https://github.com/88Mangos/88Mangos) for a CMU LaTeX (Beamer) poster template, my vimrc and zshrc setup, and LaTeX shortcuts I like to use. <br><br><b>Contact:</b> tylery [at] andrew [dot] cmu [dot] edu"
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            # - name: Coursework
            #   url: coursework/ # now hidden
            # - name: Projects
            #   url: projects/
            # - name: Algorithms 
              # url: algos/
            # deprecating because I don't think it's productive (and I also find it a little performative)
            # to create editorials for every LC problem I solve + sticking to this habit is way too cumbersome
            # especially when actual work or school kicks in.
            - name: Resume
              url: resume/
            # - name: Other
            #   url: other/
            # - name: PLACEHOLDER
            #   url: path/to/placeholder/

    socialIcons:
        - name: GitHub
          url: https://github.com/88Mangos
        - name: LinkedIn
          url: https://www.linkedin.com/in/tyler-j-yang/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=oRAc9acAAAAJ
        # - name: Email
        #   url: mailto:tylery[at]andrew[dot]cmu[dot]edu

    assets:
        disableScrollBarStyle: true
        favicon16x16: "favicon-16x16.png"
        favicon32x32: "favicon-32x32.png"
        appleTouchIcon: "apple-touch-icon.png"


# =========================================================================== #
# Rendering Engine
# =========================================================================== #
markup:
    goldmark:
        renderer:
            unsafe: true

    highlight: # code highlighting 
        guessSyntax: true # auto detect language
        style: onedark 

    tableOfContents: 
        endLevel: 3
        ordered: false
        startLevel: 1